# -*- coding: utf-8 -*-
"""AIML LAB-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1241htgM6L2knJZD8VWrM61DUPnh8V8im
"""



"""Part 1 – Implement Basic Data Structures using Numpy, Pandas
1. Lists
2. Arrays
3. Identify their type using type()

"""

import numpy as np
l1=[1,2,3,4,5]
arr1 =np.array(l1)
arr1

type(l1)

type(l1)

l2=np.array([8,9,2,4,7])
l2

"""Perform Mathematical Operations on these datasets - Multiplication, Division, Poweroff"""

print(l1*l2)
print(l2/l1)
print(l2**l1)

""". Combine text with Numpy fuction to generate a textual output - ”Addition of Two:
array1 +array 2
"""

print(l1+l2)
print(f"{l1} and {l2} together: {l1+l2}")

""". Implement np.sin(), log(), log2(), np.exp())

"""

# sine function
print(np.sin(l1))
# logarithm
print(np.log(l1))
print(np.log10(l1))
print(np.log2(l1))
# Exponential
print(np.exp(l1))

"""Part 2 – Visualization of Data using matplotlib, pyplots Packages

. Using the generated dataset given above. Generate the following graphs and justify the
relationships among the vectors.

Let's suppose we collected age (in years), height (in cm), and weight (in kilograms) information from few patients visitng a clinic.
"""

people = ['virat','raju','kruthik','roshan','omsri','saiposhan',
          'siri','hari','vijay','rahul','shiva','raj']
age = [21,12,32,45,37,18,28,52,5,40,48,15]
weight = [55,35,77,68,70,60,72,69,18,65,82,48]
height = [160,135,170,165,173,168,175,159,105,171,155,158]

import matplotlib.pyplot as plt

plt.scatter(weight, height)
plt.title("Relationship between Weight and Height of Patients")
plt.ylabel("Height in Meters")
plt.xlabel("Weight of Patients in Kgs")
plt.show()

"""# **Generate Bar Plot**"""

plt.figure(figsize=(12,4))
plt.title("People's weight in kgs",fontsize=16,
          fontstyle='italic')

# Main plot function 'bar'
plt.bar(x=people,height=weight, width=0.6,
        color='orange',edgecolor='k',alpha=0.6)

plt.xlabel("People",fontsize=15)
plt.xticks(fontsize=14,rotation=30)
plt.yticks(fontsize=14)
plt.ylabel("Weight (in kgs)",fontsize=15)
plt.show()

"""# **Generate Histogram**"""

import numpy as np
plt.figure(figsize=(7,5))

# Main plot function 'hist'
plt.hist(weight,color='red',edgecolor='k', alpha=0.75,bins=5)

plt.title("Histogram of patient weight",fontsize=18)
plt.xlabel("Weight in kgs",fontsize=15)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()

"""Part 3 – Access Data from Various Data Sources using builtin Function of Numpy, Pandas"""

import numpy as np
import pandas as pd

df1 = pd.read_table("data.tsv")

df1

data2 = pd.read_csv("data.csv")

data2

data3 = pd.read_excel("data.xlsx")

data3